DROP DATABASE IF EXISTS Faculty_Research;
CREATE DATABASE Faculty_Research;

USE Faculty_Research;

DROP TABLE IF EXISTS public;
CREATE TABLE IF NOT EXISTS public
(
  publicID INT NOT NULL AUTO_INCREMENT,
  firstName VARCHAR(255) NOT NULL,
  lastName VARCHAR(255) NOT NULL,
  userName VARCHAR(255) NOT NULL,
  pubEmail VARCHAR(255) NOT NULL,
  InterestId VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  PRIMARY KEY (publicID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS topic;
CREATE TABLE IF NOT EXISTS topic
(
  topicID INT NOT NULL AUTO_INCREMENT,
  topicDescribtion VARCHAR(255) NOT NULL,
  topicTag VARCHAR(20) NOT NULL,
  PRIMARY KEY (topicID)
)  ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS student;
CREATE TABLE IF NOT EXISTS student
(
  studentID INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  interestID VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  PRIMARY KEY (studentID),
  FOREIGN KEY (publicID) REFERENCES user(publicID)
            ON DELETE CASCADE
            ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS faculty;
CREATE TABLE IF NOT EXISTS faculty
(
  facultyID INT NOT NULL AUTO_INCREMENT,
  department VARCHAR(255) NOT NULL,
  abstract VARCHAR(255) NOT NULL,
  publicID INT NOT NULL,
  subjectID INT NOT NULL,
  PRIMARY KEY (facultyID),
  FOREIGN KEY (publicID) REFERENCES public(publicID)
            ON DELETE CASCADE
            ON UPDATE CASCADE,
  FOREIGN KEY (topicID) REFERENCES topic(topicID)
            ON DELETE CASCADE
            ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS department;
CREATE TABLE IF NOT EXISTS department
(
  departmentID INT NOT NULL,
  departmentName VARCHAR(255) NOT NULL,
  universityID VARCHAR(10) NOT NULL,
  PRIMARY KEY (departmentID),
    FOREIGN KEY (universityID) REFERENCES university(universityID)
            ON DELETE CASCADE
            ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS university;
CREATE TABLE IF NOT EXISTS university
(
  universityID INT NOT NULL,
  universityName VARCHAR(255) NOT NULL,
  PRIMARY KEY (universityID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;


